name: Linux

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - run: yarn install

      - run: yarn build
